 How many distinct countries are represented in the dataset?

In [40]:
import polars as pl
from pathlib import Path

In [41]:
CURRENT_DIR=Path.cwd()

PROJECT_PATH=CURRENT_DIR.parent

print("project_path:",PROJECT_PATH)

project_path: /Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis

In [42]:
# Search all parquet files in the whole project
all_parquet_files = list(PROJECT_PATH.rglob("*.parquet"))

# Show all found parquet files
all_parquet_files

[PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/tournament_clean.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/statistics_clean.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/event.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/season_clean.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/tennis_power_clean.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/votes_clean.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/time_clean.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/venue_clean.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/odds_clean.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/round_clean.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/point_by_point_clean.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/away_and_home_team/home_team.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/away_and_home_team/away_team.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/away_and_home_score/home_team_score.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/away_and_home_score/away_team_score.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/away_team_score_12130240.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/away_team_12128274.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/votes_12127475.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/time_12132143.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/statistics_12130651.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/statistics_12129397.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/tournament_12132843.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/home_team_score_12121683.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/away_team_12128264.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/pbp_12127476.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/home_team_12128217.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/home_team_score_12132690.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/away_team_score_12127652.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/event_12127651.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/venue_12129847.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/away_team_score_12126220.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/statistics_12121677.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/event_12127729.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/away_team_score_12131896.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/statistics_12109849.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/event_12132266.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/away_team_score_12127642.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/event_12127739.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/venue_12127737.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/votes_12121604.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/pbp_12126651.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/time_12109843.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/tournament_12128245.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/pbp_12133078.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/away_team_score_12130773.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/odds_12128407.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/votes_12131773.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/home_team_12133492.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/tournament_12130289.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/venue_12127441.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/power_12132785.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/time_12127047.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/away_team_12128757.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/power_12129433.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/votes_12130311.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/round_12127788.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/round_12129171.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/home_team_score_12127784.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/tournament_12129627.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/venue_12127451.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/time_12133012.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/tournament_12131793.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/tournament_12128410.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/venue_12126666.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/votes_12126219.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/statistics_12127770.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/votes_12129873.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/home_team_12128161.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/statistics_12129810.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/odds_12128252.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/power_12129276.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/round_12131680.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/venue_12130053.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/home_team_12109898.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/home_team_12128171.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/time_12127612.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/home_team_12127282.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/away_team_score_12127371.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/statistics_12129800.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/odds_12128242.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/away_team_12139609.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/pbp_12129870.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/statistics_12127760.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/time_12129193.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/odds_12129630.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/home_team_12124909.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/statistics_12127805.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/power_12109879.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/venue_12129379.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/round_12127659.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/home_team_score_12127655.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/time_12128265.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/round_12129841.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/time_12127196.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/odds_12125055.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/statistics_12129775.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/tournament_12134074.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/round_12127649.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/power_12128180.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/home_team_score_12132262.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/home_team_12132131.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/away_team_12132142.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/round_12127731.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/home_team_12126985.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/time_12128275.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/round_12132316.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/odds_12134073.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/round_12133121.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/votes_12129153.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/tournament_12127622.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/season_12128173.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/season_12127280.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/power_12133463.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/season_12129511.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/season_12130836.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/odds_12127108.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/season_12128163.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/tournament_12127632.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/power_12133473.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/odds_12130237.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/home_team_12130104.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/votes_12132972.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/tournament_12131371.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/power_12129830.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/power_12127750.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/power_12125048.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/tournament_12130703.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/event_12128236.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/venue_12128238.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/round_12130055.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/time_12121870.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/votes_12126927.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/odds_12130141.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/home_team_score_12133333.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/time_12128756.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/power_12127628.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/statistics_12132098.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/extracted/20240306/power_12127740.parquet'),

In [44]:
# List all parquet files in Data folder

data_path = PROJECT_PATH / "tennis_data" / "Data"

parquet_files=list(data_path.rglob("*.parquet"))

for file in parquet_files:
    print(file)
    
    
print("\nData_path:",data_path)

print("\nfolder exists:",data_path.exists())

/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/tournament_clean.parquet
/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/statistics_clean.parquet
/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/event.parquet
/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/season_clean.parquet
/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/tennis_power_clean.parquet
/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/votes_clean.parquet
/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/time_clean.parquet
/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/venue_clean.parquet
/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/odds_clean.parquet
/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/round_clean.parquet
/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/point_by_point_clean.parquet
/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/away_and_home_team/home_team.parquet
/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/away_and_home_team/away_team.parquet
/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/away_and_home_score/home_team_score.parquet
/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/away_and_home_score/away_team_score.parquet

Data_path: /Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data

folder exists: True

In [45]:

country_files = []

for file in data_path.rglob("*.parquet"):
    try:
        df = pl.read_parquet(file, n_rows=1)

        if "country" in df.columns:
            country_files.append(file)
            print(file.name, "---->", "country found")

    except Exception as e:
        pass

country_files

venue_clean.parquet ----> country found
home_team.parquet ----> country found
away_team.parquet ----> country found

[PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/venue_clean.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/away_and_home_team/home_team.parquet'),
 PosixPath('/Users/macbook/Desktop/ data_analysis_tannis projects/tennis_data_analysis/tennis_data/Data/away_and_home_team/away_team.parquet')]

In [8]:


home_team=pl.read_parquet(
    PROJECT_PATH/"tennis_data"/"Data"/"away_and_home_team"/"home_team.parquet" 
    )
away_team=pl.read_parquet(
    PROJECT_PATH/"tennis_data"/"Data"/"away_and_home_team"/"away_team.parquet"
)

In [34]:
home_team.select("country").head()

shape: (5, 1)
┌─────────┐
│ country │
│ ---     │
│ str     │
╞═════════╡
│ France  │
│ France  │
│ France  │
│ France  │
│ Croatia │
└─────────┘

In [35]:
away_team.select("country").head()

shape: (5, 1)
┌─────────┐
│ country │
│ ---     │
│ str     │
╞═════════╡
│ Canada  │
│ Canada  │
│ Italy   │
│ Italy   │
│ Spain   │
└─────────┘

In [36]:
countries = pl.concat(
    [
        home_team.select("country"),
        away_team.select("country")
    ]
)

In [37]:
countries_clean = countries.filter(
    pl.col("country").is_not_null()
)

In [38]:
distinct_countries = countries_clean.select(
    pl.col("country").n_unique()
)

distinct_countries

shape: (1, 1)
┌─────────┐
│ country │
│ ---     │
│ u32     │
╞═════════╡
│ 101     │
└─────────┘

In [39]:
countries_clean.select(
    "country"
).unique()

shape: (101, 1)
┌────────────┐
│ country    │
│ ---        │
│ str        │
╞════════════╡
│ Belarus    │
│ Algeria    │
│ Slovenia   │
│ Colombia   │
│ Sweden     │
│ …          │
│ Costa Rica │
│ Estonia    │
│ China      │
│ Barbados   │
│ Bahamas    │
└────────────┘

## Objective

The objective of this analysis is to determine the number of unique countries represented by tennis players in the dataset.

## Data Used

The player information was extracted from the following tables:

- MatchHomeTeamInfo
- MatchAwayTeamInfo

The relevant feature used for this analysis was:

- country

This column represents the player's country/nationality.

## Data Preparation

Since a player can appear as either a home player or an away player, both player datasets were combined to include all participants.

Missing country values were removed because they do not provide valid country information.

## Important Note

The dataset also contains a country column in the MatchVenueInfo table.

However, this column represents the location of the venue where the match was played, not the player's country.

Therefore, venue country information was not used in this analysis because the goal was to identify the countries represented by tennis players.

## Method

The number of distinct countries was calculated by counting the unique values in the player's country column.

## Result

The analysis shows that the dataset contains:

101 distinct countries

represented by tennis players.

## Conclusion

The dataset includes players from a diverse range of countries, with 101 unique player countries represented.

This result reflects the nationality distribution of players included in the dataset, rather than the countries where tournaments were hosted.